name: S&P 500 Monitor with Web Dashboard

on:
  schedule:
    # Run every hour from 9 AM to 4 PM ET, Monday to Friday
    - cron: '0 14-21 * * 1-5'  # UTC time (ET + 5 hours)
  workflow_dispatch:  # Allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy matplotlib plotly seaborn pytz
        
    - name: Run S&P 500 analysis (Full Version)
      run: |
        python sp500_monitor.py || echo "Full version failed, trying simple version"
        
    - name: Run Simple Dashboard (Backup)
      run: |
        python simple_dashboard.py
        
    - name: List generated files
      run: |
        ls -la *.html *.png *.json *.log || echo "Some files missing"
        
    - name: Create index.html
      run: |
        if [ -f "sp500_dashboard.html" ]; then
          cp sp500_dashboard.html index.html
        else
          echo "Dashboard file not found" > index.html
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        keep_files: false
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sp500-analysis-${{ github.run_number }}
        path: |
          *.html
          *.png
          *.json
          *.log
